### PR TITLE
Drop extra date from man page

### PR DESCRIPTION
**Pull request by bmwiedemann**
to allow for reproducible builds

See https://reproducible-builds.org/ for why this matters.

### CODE REVIEW

**Comment by bmwiedemann** [comment]
Is there anything I can do to help get this simple patch merged?

**Comment by nipunn1313** [comment]
Hi. Thanks for the contribution.
This code looks fine for what it is trying to do.

I am curious why the man page is important for reproducible builds. Generally reproducible builds are talking about the binary output rather than the man pages. Just would like to know the use case to warrant the change. Otherwise, this looks good.

**Comment by bmwiedemann** [comment]
We aim to build completely reproducible Linux distributions, so we try to get bit-by-bit reproducible rpm/deb packages and those include man pages.
It is true that it does not contribute much to the security-aspect of reproducible builds, but it helps with other aspects such as 
* giving smaller deltas
* making diffs easier to read
* (for openSUSE with OBS) avoiding automatic rebuilds of depending packages
* saving bandwidth of mirrors and users (by not publishing automatic rebuilds that gave the same binary)

**Comment by nipunn1313** [comment]
This lgtm. Thank you!

**Pull request merged**
