### PR TITLE
Remove inclusion of deprecated nautilus extension headers.

### PR DESCRIPTION
**Pull request by e7appew**

### CODE REVIEW

**Comment by samertm** [comment]
Thanks for the patch! If you don't mind me asking, how do you know that those headers are deprecated? The docs still tell folks to import them: https://developer.gnome.org/libnautilus-extension/3.24/NautilusFileInfo.html

**Comment by e7appew** [comment]
I've been compiling it on Debian unstable, which currently has version 3.30.5 of nautilus. I checked the source code of nautilus, and the headers were deprecated in version 3.27, so maybe you should hold off on the merge if you still need to support older versions. I'm not sure if there's an easy was of including the right headers with conditional compilation.

**Comment by ernestask** [comment]
I deprecated direct inclusion of those headers, this is correct. The link to the docs is for version 3.24, so, obviously, that is a poor reference to use. However, due to reasons, the online documentation is not updated for new releases, so I will need to work around that issue.

**Comment by ernestask** [comment]
https://gitlab.gnome.org/GNOME/nautilus/blob/c397369f87320a0ee8276a3482ffaad1bb50c794/libnautilus-extension/nautilus-file-info.h#L27 would be an example.

**Comment by goffrie** [comment]
Well this is extremely delayed, but thanks for the PR 😅 

> ❌ goffrie

silly CLA bot...

**Pull request merged**
