### PR TITLE
fix #15

### LINKED ISSUE #15: Dropbox tray icon not working in XFCE & LXDE
[See downstream bug on Launchpad for details.](https://bugs.launchpad.net/ubuntu/+source/nautilus-dropbox/+bug/1546176)

### PR DESCRIPTION
**Pull request by naftalmm**
Worked for me. Tested on Xubuntu 16.04.

### CODE REVIEW

**Comment by nipunn1313** [comment]
Hi - thanks for the contribution.

Do you know if this will cause a regression on any of the other supported setups (eg Ubuntu, Fedora)? Is `dbus-launch` always available?

Thanks
--Nipunn

**Comment by nipunn1313** [comment]
Can you make sure to sign the CLA as well
thanks!
https://opensource.dropbox.com/cla/

**Comment by naftalmm** [comment]
Ok, I`ve signed CLA.

> Is dbus-launch always available?

According to [https://pkgs.org](https://pkgs.org/download//usr/bin/dbus-launch) it should by present in majority of popular Linux distriubtives including Ubuntu & Fedora (or at least it's available in their repos), so it's highly unlikely, that it will cause a regression for this distibutives.
Moreover, maybe it will even fix the same bug for Ubuntu (#38).

**Comment by nipunn1313** [comment]
Ok sounds good! Thank you.
CC @samertm for heads up

**Pull request merged**
